### ISSUE TITLE
Crash while trying to download system update

### ISSUE THREAD

**Issue by garoxas** [DrHacknik/3DNUS#20]
I was trying to download 3DS update 11.7.0-40 using 3DNUS (tried both v3.1.11 alpha and v3.2 nightly) but while downloading certain files it'll crash as can be seen below

![3dnus](https://user-images.githubusercontent.com/11901820/41809359-77c8db08-7716-11e8-8bd5-93a497be9c1a.png)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.UnauthorizedAccessException: Access to the path 'H:\Program\Console\Nintendo 3DS\3DSNUS\tmp\tmd.__SyncDownTMP_52.2114713702298__.bak.tmp' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at MarcusD.at.SyncDown.syncDown(String link, String to)
   at _3DNUS_Material_Edition.FormMain.singledownload(UInt64 id, Int32 version)
   at _3DNUS_Material_Edition.FormMain.firmwdownload(YLS_Sysver sys, Char region)
   at _3DNUS_Material_Edition.FormMain.materialFlatButton1_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2671.0 built by: NET471REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
3DNUS Material Edition
    Assembly Version: 3.2.0.0
    Win32 Version: 3.2
    CodeBase: file:///H:/Program/Console/Nintendo%203DS/3DSNUS/3DNUS%20Material%20Edition.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
MaterialSkin
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///H:/Program/Console/Nintendo%203DS/3DSNUS/MaterialSkin.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2661.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
AxInterop.WMPLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///H:/Program/Console/Nintendo%203DS/3DSNUS/AxInterop.WMPLib.DLL
----------------------------------------
Interop.WMPLib
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///H:/Program/Console/Nintendo%203DS/3DSNUS/Interop.WMPLib.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

on Win10 x64 and plenty of hard disk space

**Comment by garoxas** [comment]
running the app as administrator works though

**Comment by DrHacknik** [comment]
[LOG_DUMP.log](https://github.com/DrHacknik/3DNUS/files/2137498/LOG_DUMP.log)
![image](https://user-images.githubusercontent.com/7658605/41918124-b2c89f44-7929-11e8-9aa2-6941f575012f.png)

As you can see, it downloads just fine for me. As well as pack everything correctly. I did not run the program as Admin, nor is it stored in a strange user directory. For example, try storing 3DNUS within your Documents directory. Sometimes storing it outside of the user directory can cause permissions issues.

**Comment by garoxas** [comment]
pretty sure I run it from a directory with no special permission, and it only happens after downloading several files
I guess there's something wrong while trying to delete and create tmp folder multiple times in a very short timespan

well as I can just run it as admin, you're welcome to close this issue if you want. but I'd say how about if you look at the solution here https://stackoverflow.com/a/11523266 and see if it can be implemented
thanks a lot

**Comment by DrHacknik** [comment]
Thanks for your input mate!
